### ISSUE TITLE
FTBFS on AArch64 Darwin due to failed alignment assertion

### ISSUE THREAD

**Issue by jchadwick-buf** [google/cel-cpp#831]
Unfortunately, it seems that compatibility with some ABIs was probably broken in abbbf51fa6ad675e0b081c4f43b1ad76806401d8.

```console
ERROR: /Users/john/Code/cel-cpp/internal/BUILD:39:11: Compiling internal/new.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //internal:new) external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 27 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
internal/new.cc:55:1: error: static assertion failed due to requirement 'IsAligned(alignof(long double), 16UL)'
static_assert(IsAligned(alignof(std::max_align_t)
```

The reasoning for this assertion to fail is [explained well in this Stack Overflow answer](https://stackoverflow.com/a/56171758), though currently it is unclear to me whether the code actually is broken. I'm not sure why this assertion failing would cause any problems.

**Comment by kyessenov** [comment]
@jcking Any thoughts on this issue? I think this breaks macos toolchain.

**Comment by jcking** [comment]
I believe I removed this assertion last week. Removing it should be safe.
