### ISSUE TITLE
Add compatibility with abseil 20250512.1

### ISSUE THREAD

**Issue by mering** [google/cel-cpp#1630]
cel-cpp `v0.12.0` (and `head`) are not compatible with latest abseil-cpp (`20250512.1`).

Reproduction:
```starlark
# MODULE.bazel
bazel_dep(
  name = "abseil-cpp",
  #version = "20250127.1",  # always works
  version = "20250512.1",  # requires protobuf 30
)
bazel_dep(
  name = "cel-cpp",
  #version = "0.11.0",  # always works
  version = "0.12.0",  # only works with abseil-cpp 20250127.1
)
bazel_dep(name = "protobuf", version = "30.0")
```

Build (tested with clang 19):
```sh
USE_BAZEL_VERSION=8.x CC=clang bazelisk build @cel-cpp//common:type
```

<details>
<summary>Error</summary>
<pre>
In file included from external/cel-cpp+/common/typeinfo.cc:15:
external/cel-cpp+/common/typeinfo.h:156:67: error: expected ')'
  156 |   constexpr explicit TypeInfo(const std::type_info* ABSL_NULLABLE rep)
      |                                                                   ^
external/cel-cpp+/common/typeinfo.h:156:30: note: to match this '('
  156 |   constexpr explicit TypeInfo(const std::type_info* ABSL_NULLABLE rep)
      |                              ^
external/cel-cpp+/common/typeinfo.h:159:38: error: expected ';' at end of declaration list
  159 |   const std::type_info* ABSL_NULLABLE rep_ = nullptr;
      |                                      ^
      |                                      ;
external/cel-cpp+/common/typeinfo.h:133:16: error: no member named 'rep_' in 'cel::TypeInfo'
  133 |     return lhs.rep_ == rhs.rep_ ||
      |            ~~~ ^
external/cel-cpp+/common/typeinfo.h:133:28: error: no member named 'rep_' in 'cel::TypeInfo'
  133 |     return lhs.rep_ == rhs.rep_ ||
      |                        ~~~ ^
external/cel-cpp+/common/typeinfo.h:134:17: error: no member named 'rep_' in 'cel::TypeInfo'
  134 |            (lhs.rep_ != nullptr && rhs.rep_ != nullptr &&
      |             ~~~ ^
external/cel-cpp+/common/typeinfo.h:134:40: error: no member named 'rep_' in 'cel::TypeInfo'
  134 |            (lhs.rep_ != nullptr && rhs.rep_ != nullptr &&
      |                                    ~~~ ^
external/cel-cpp+/common/typeinfo.h:135:18: error: no member named 'rep_' in 'cel::TypeInfo'
  135 |             *lhs.rep_ == *rhs.rep_);
      |              ~~~ ^
external/cel-cpp+/common/typeinfo.h:135:31: error: no member named 'rep_' in 'cel::TypeInfo'
  135 |             *lhs.rep_ == *rhs.rep_);
      |                           ~~~ ^
external/cel-cpp+/common/typeinfo.h:145:26: error: no member named 'rep_' in 'cel::TypeInfo'
  145 |                       id.rep_ != nullptr ? id.rep_->hash_code() : size_t{0});
      |                       ~~ ^
external/cel-cpp+/common/typeinfo.h:145:47: error: no member named 'rep_' in 'cel::TypeInfo'
  145 |                       id.rep_ != nullptr ? id.rep_->hash_code() : size_t{0});
      |                                            ~~ ^
external/cel-cpp+/common/typeinfo.h:157:14: error: use of undeclared identifier 'rep'
  157 |       : rep_(rep) {}
      |              ^
external/cel-cpp+/common/typeinfo.h:157:9: error: member initializer 'rep_' does not name a non-static data member or base class
  157 |       : rep_(rep) {}
      |         ^~~~~~~~~
external/cel-cpp+/common/typeinfo.h:156:22: warning: constexpr constructor that does not initialize all members is a C++20 extension [-Wc++20-extensions]
  156 |   constexpr explicit TypeInfo(const std::type_info* ABSL_NULLABLE rep)
      |                      ^
external/cel-cpp+/common/typeinfo.h:159:25: note: member not initialized by constructor
  159 |   const std::type_info* ABSL_NULLABLE rep_ = nullptr;
      |                         ^
external/cel-cpp+/common/typeinfo.cc:48:7: error: use of undeclared identifier 'rep_'
   48 |   if (rep_ == nullptr) {
      |       ^
external/cel-cpp+/common/typeinfo.cc:63:27: error: use of undeclared identifier 'rep_'
   63 |       abi::__cxa_demangle(rep_->name(), nullptr, &length, &status));
      |                           ^
external/cel-cpp+/common/typeinfo.cc:65:24: error: use of undeclared identifier 'rep_'
   65 |     return std::string(rep_->name());
      |                        ^
1 warning and 15 errors generated.
</pre>
</details>

I bisected the breaking commit in cel-cpp to ab4f82684486a995e246818a82c3e8d9e0de1df4 and in abseil-cpp to abseil/abseil-cpp@48f0f9168783af032582d6e27c7b8c06066c218f.

**Comment by mering** [comment]
Fixed in e78965a8c335d1c7445fcf95e250181a78d4deff.
